spring:
  application:
    name: NotificationService

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.CptFranck.dto"

server:
  port: 8085

# Keycloak variable
keycloak:
  auth:
    token:
      ressource-id: ticketing-client-id
      principal-attribute: preferred_username
    jwk-set-uri: http://localhost:8091/realms/ticketing-security-realm/protocol/openid-connect/certs

# security config variables
security:
  cors:
    allowed-origins: http://localhost:4200, http://localhost:63342

#logging:
#  level:
#    root: debug